### ISSUE TITLE
Use the edn reader

### ISSUE THREAD

**Issue by bensu** [tailrecursion/ring-edn#6]
Since the incoming request can come from untrusted sources it would be more appropriate to use [`clojure.edn/read-string`](https://clojure.github.io/clojure/clojure.edn-api.html) instead of `clojure.core/read-string`. It could also take an `opts` map with custom `:readers`, `:eof`, and `:default`, like `clojure.edn/read-string` does:

```clj
(wrap-edn-params handler {:readers {'my-project/tag #'my-reader}})
```

If it's within scope, I'll gladly submit a patch for it.

**Comment by fogus** [comment]
It's definitely within scope.

**Comment by bensu** [comment]
PR in #8

I apologize, when I proposed using `clojure.edn/read-string` I was looking at old source as found in [crossclj](https://crossclj.info/ns/ring-edn/0.1.0/ring.middleware.edn.html). The PR was pretty straightforward since newer versions of `ring-edn` already use `clojure.edn/read-string`.
